#!/bin/bash
# PreToolUse hook (Edit|Write): blocks edits to files that must never be
# hand-modified. Exit 2 = block the tool call and feed stderr back to Claude.

input=$(cat)
file_path=$(printf '%s' "$input" | python3 -c \
  "import json,sys; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))" 2>/dev/null)

[ -z "$file_path" ] && exit 0

case "$file_path" in
  *package-lock.json)
    echo "BLOCKED: package-lock.json is generated by npm. Run 'npm install <pkg>' instead of editing it." >&2
    exit 2
    ;;
  */node_modules/*)
    echo "BLOCKED: never edit files inside node_modules/." >&2
    exit 2
    ;;
esac

exit 0
